server:
  port: 8080
  servlet:
    context-path: /trabalhabrasil

logging:
  level:
    root: debug

trabalhaBrasil:
  url: https://www.trabalhabrasil.com.br/api/v1.0/
salarioBR:
  url: https://salariobr.com/api/
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: FULL
